name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'disabled-main'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - 'disabled-main'
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

env:
  PUBLIC_SITE_HOSTNAME: nemanjam.github.io

jobs:
  # build with astro action, no monorepo
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout your repository using git
  #       uses: actions/checkout@v3
  #     - name: Install, build, and upload your site
  #       uses: withastro/action@v1
  #       # args for monorepo?
  #       with:
  #         path: apps/nemanjamiticcom
  #         node-version: 20.10.0
  #         package-manager: yarn@latest 

  build-monorepo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Print commit id, message and tag
        run: |
          git show -s --format='%h %s'
          echo "github.ref -> {{ github.ref }}"

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
          registry-url: 'https://registry.yarnpkg.com'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build nemanjam.github.io
        run: yarn build:nmc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./apps/nemanjamiticcom/dist

  deploy:
    needs: build-monorepo
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1